input files for cloud cost with surface wind
JCSDA-internal/ufo-data pull request #337
Opened 2023-06-05 13:19 UTC by stemiglio

## Description

This change adds the input files for testing the calculation of the cloud cost used for quality control when surface winds are also included in the state vector. 

## Dependencies

This PR is required by JCSDA-internal/ufo/pull/2851

2023-06-05 14:58 UTC, DJDavies2 commented
I run the ufo ctests with the ufo branch and this ufo-data branch and still got a failure:

ufo_test_tier1_test_ufo_function_cloudcost_surfwind:

 2023/06/05  14:38:57  fatal error in module /home/d03/frwd/cylc-run/ufo-2851/share/mo-bundle/rttov/src/rttov/coef_io/rttov_coef_io_mod.F90:0163
     Cannot find any coefficient file named: Data//rtcoef_gpm_1_gmi.dat/.bin/.h5/.H5
 2023/06/05  14:38:57  fatal error in module /home/d03/frwd/cylc-run/ufo-2851/share/mo-bundle/rttov/src/rttov/coef_io/rttov_read_coefs.F90:0238
     
fatal error reading coefficients: rtcoef_gpm_1_gmi
OOPS Ending   2023-06-05 14:38:57 (UTC+0000)
Rank 0 [Mon Jun  5 14:38:57 2023] [c2-0c2s11n1] application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

2023-06-06 08:44 UTC, smnewman approved these changes
Thanks @stemiglio, I can see the test files contain 11 locations with observations comprising 4 channels (10-13). Assuming the ctest passes with 1.0e-5 tolerance this looks good.

2023-06-06 09:56 UTC, smnewman commented
> I run the ufo ctests with the ufo branch and this ufo-data branch and still got a failure:
>
> ufo_test_tier1_test_ufo_function_cloudcost_surfwind:
>
> 2023/06/05 14:38:57 fatal error in module /home/d03/frwd/cylc-run/ufo-2851/share/mo-bundle/rttov/src/rttov/coef_io/rttov_coef_io_mod.F90:0163
> Cannot find any coefficient file named: Data//rtcoef_gpm_1_gmi.dat/.bin/.h5/.H5
2023/06/05 14:38:57 fatal error in module /home/d03/frwd/cylc-run/ufo-2851/share/mo-bundle/rttov/src/rttov/coef_io/rttov_read_coefs.F90:0238
>
> fatal error reading coefficients: rtcoef_gpm_1_gmi
OOPS Ending 2023-06-05 14:38:57 (UTC+0000)
Rank 0 [Mon Jun 5 14:38:57 2023] [c2-0c2s11n1] application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

@david-rundle do the RTTOV ctests rely on coefficients in https://github.com/JCSDA-internal/rttov/tree/develop/rtcoef_rttov12/rttov7pred54L? (If so, then we would need to add `rtcoef_gpm_1_gmi.dat`?)

2023-06-06 10:31 UTC, stemiglio commented
See https://github.com/JCSDA-internal/rttov/pull/32 where `rtcoef_gpm_1_gmi.dat` is added

2023-06-06 15:52 UTC, DJDavies2 approved these changes

2023-06-06 16:43 UTC, fcvdb approved these changes
There are some warnings when reading file:
 `Data/ufo/testinput_tier_1/jopa_gmihigh_20210701T1200Z_out_m.nc4` 
in test:
 `ufo_test_tier1_test_ufo_function_cloudcost_surfwind `

```
149: WARNING: ioda::Variable: hdf and netcdf fill value specifications do not match.
149:     hdf fill value property: 9.96921e+36
149:     netcdf _FillValue attribute: -3.3688e+38
149: WARNING: selecting the netcdf _FillValue attribute value: -3.3688e+38
```

```
149:     hdf fill value property: -2147483647
149:     netcdf _FillValue attribute: -2147483643
149: WARNING: selecting the netcdf _FillValue attribute value: -2147483643
149: WARNING: ioda::Variable: hdf and netcdf fill value specifications do not match.
```

2023-06-16 01:36 UTC, PatNichols requested changes

2023-06-16 01:36 UTC, PatNichols commented on testinput_tier_1/jopa_gmihigh_20210701T1200Z_out_m.nc4
This file seems a little large...Is it possible to shrink it down some ? Thanks.

2023-06-16 16:38 UTC, stemiglio commented on testinput_tier_1/jopa_gmihigh_20210701T1200Z_out_m.nc4
I have just upload a smaller test file and checked that the test still pass

2023-06-20 13:54 UTC, closed without merging